import type { NextPage } from 'next';
import Head from 'next/head';
import React, { useContext, useState } from 'react';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import {
  Web3Context,
  ellipseAddress,
  formatBigNumWithDecimals,
} from 'algo-web3';

const Home: NextPage = () => {
  const [balance, setBalance] = useState(0);
  const { web3 } = useContext(Web3Context);
  if (!web3) {
    return <div>Loading...</div>;
  }
  if (web3.wallet.isConnected()) {
    web3
      .fetchAccountInformation()
      .then((value: Record<string, any>) => setBalance(value.amount));
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          Select Algorand Network:{' '}
          <select
            value={web3.currentNetworkIndex}
            onChange={(e: React.ChangeEvent<HTMLSelectElement>) =>
              web3.switchNetwork(parseInt(e.target.value))
            }
          >
            {web3.networks.map((network, i) => {
              return (
                <option value={i} key={i}>
                  {network.name}
                </option>
              );
            })}
          </select>
        </div>
        <hr />
        <h1 className={styles.title}>
          Welcome to{' '}
          <a href="https://github.com/kadirpekel/algo-web3">Algo-Web3</a> Demo
        </h1>

        <p className={styles.description}>
          Get started by connecting your wallet:{' '}
          {web3.wallet.isConnected() ? (
            <button onClick={() => web3.wallet.disconnect()}>Disconnect</button>
          ) : (
            <button onClick={() => web3.wallet.connect()}>
              Connect your Algorand Wallet
            </button>
          )}
        </p>
        {web3.wallet.isConnected() && (
          <div className={styles.grid}>
            <div className={styles.card}>
              <h2>Account Info:</h2>
              <p>Wallet Address: {ellipseAddress(web3.wallet.getAccount())}</p>
            </div>

            <div className={styles.card}>
              <h2>Balance</h2>
              <p>
                Algos in Wallet: {formatBigNumWithDecimals(BigInt(balance), 2)}
              </p>
            </div>
          </div>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
