import type { NextPage } from 'next';
import React, { useContext } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Web3Context } from 'algo-web3';

const Home: NextPage = () => {
  const { web3 } = useContext(Web3Context);

  if (!web3) {
    return <div>Loading...</div>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>React Demo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <select
            value={web3.currentNetworkIndex}
            onChange={(e) => web3.switchNetwork(parseInt(e.target.value))}
          >
            {web3.networks.map((network, i) => {
              return (
                <option value={i} key={i}>
                  {network.name}
                </option>
              );
            })}
          </select>
        </div>
        <h1 className={styles.title}>React Demo App</h1>
      </main>

      <footer className={styles.footer}>
        <a href="https://github.com/kadirpekel/algo-web3">Github</a>
      </footer>
    </div>
  );
};

export default Home;
